# Generated by Django 3.1.7 on 2021-03-26 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=50)),
                ('generic_name', models.CharField(max_length=50)),
                ('unit_sell_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unit_purchase_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('medicine_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'medicine_data',
            },
        ),
        migrations.CreateModel(
            name='MedicineToVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.CharField(max_length=10)),
                ('vendor_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'vendor_to_medicine',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_number', models.BigIntegerField()),
                ('bill', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'sales_data',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.CharField(max_length=10)),
                ('batch_id', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('threshold', models.IntegerField(default=50)),
                ('expiry_date', models.DateField()),
            ],
            options={
                'db_table': 'stock_data',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('vendor_id', models.CharField(max_length=10)),
                ('medicine_ids', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vendor_data',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(verbose_name='DOB')),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('is_admin', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_data',
            },
        ),
    ]
