# Generated by Django 3.1.7 on 2021-03-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='medicine_ids',
            field=models.CharField(default='MED', max_length=100),
        ),
        migrations.AddField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_id',
            field=models.CharField(default='MED', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='bill',
            field=models.CharField(default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer_name',
            field=models.CharField(default='default customer', max_length=100),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='threshold',
            field=models.IntegerField(default=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_id',
            field=models.CharField(default='VEN', max_length=10, null=True),
        ),
    ]
