# Generated by Django 3.1.7 on 2021-04-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msa_app', '0004_auto_20210328_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_copy',
        ),
    ]
