# Generated by Django 3.1.7 on 2021-04-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_app', '0005_auto_20210404_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredMedicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.CharField(default='MED', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'expired_medicines',
            },
        ),
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.CharField(default='MED', max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('threshold', models.IntegerField(default=50, null=True)),
            ],
            options={
                'db_table': 'medicine_stock',
            },
        ),
    ]
