# Generated by Django 3.1.7 on 2021-04-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_app', '0006_expiredmedicines_medicinestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_copy',
            field=models.CharField(default='Not available', max_length=50, null=True),
        ),
    ]
