# Generated by Django 3.1.7 on 2021-04-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_app', '0007_auto_20210405_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='vendor_id',
            field=models.CharField(default='VEN', max_length=10),
        ),
    ]
