# Generated by Django 3.1.7 on 2021-04-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msa_app', '0009_auto_20210405_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='date',
        ),
    ]
